### ISSUE TITLE
BUG processing.core.PVector.normal is not found

### ISSUE THREAD

**Issue by teonlamont** [OpenBCI/OpenBCI_Processing#29]
I'm getting an error about `processing.core.PVector.normalize`. this function is not being found.

@taolin1992, do you have this same problem? I see it with both the https://github.com/OpenBCI/OpenBCI_Processing_3 and the `v3.0` branch.

```java
java.lang.RuntimeException: java.lang.NoSuchMethodError: processing.core.PVector.normalize()V
	at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:370)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: processing.core.PVector.normalize()V
	at org.gwoptics.graphics.graph2D.Axis2D.setAxesDirection(Unknown Source)
	at org.gwoptics.graphics.graph2D.Graph2D.<init>(Unknown Source)
	at OpenBCI_GUI$Gui_Manager.<init>(OpenBCI_GUI.java:3329)
	at OpenBCI_GUI.initializeGUI(OpenBCI_GUI.java:411)
	at OpenBCI_GUI.initSystem(OpenBCI_GUI.java:335)
	at OpenBCI_GUI$ControlPanel.CPmouseReleased(OpenBCI_GUI.java:2472)
	at OpenBCI_GUI.mouseReleased(OpenBCI_GUI.java:1018)
	at processing.core.PApplet.mouseReleased(PApplet.java:2773)
	at processing.core.PApplet.handleMouseEvent(PApplet.java:2682)
	at processing.core.PApplet.dequeueEvents(PApplet.java:2596)
	at processing.core.PApplet.handleDraw(PApplet.java:2407)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:654)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:691)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:673)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:442)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:680)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:77)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:451)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by taolin1992** [comment]
I ran into this problem before. This should be resolved after I recompiled
the new gwoptics.jar file. I can run with the
https://github.com/OpenBCI/OpenBCI_Processing_3 code on my laptop. I'm not
quite sure about the reason. Have you replaced the libraries
in Document/Processing folder with the new ones?

Tao

On Wed, Nov 18, 2015 at 6:30 PM, Teon L Brooks <notifications@github.com>
wrote:

> I'm getting an error about processing.core.PVector.normalize. this
> function is not being found.
>
> @taolin1992 <https://github.com/taolin1992>, do you have this same
> problem? I see it with both the
> https://github.com/OpenBCI/OpenBCI_Processing_3 and the v3.0 branch.
>
> java.lang.RuntimeException: java.lang.NoSuchMethodError: processing.core.PVector.normalize()V
>     at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:370)
>     at java.lang.Thread.run(Thread.java:745)Caused by: java.lang.NoSuchMethodError: processing.core.PVector.normalize()V
>     at org.gwoptics.graphics.graph2D.Axis2D.setAxesDirection(Unknown Source)
>     at org.gwoptics.graphics.graph2D.Graph2D.<init>(Unknown Source)
>     at OpenBCI_GUI$Gui_Manager.<init>(OpenBCI_GUI.java:3329)
>     at OpenBCI_GUI.initializeGUI(OpenBCI_GUI.java:411)
>     at OpenBCI_GUI.initSystem(OpenBCI_GUI.java:335)
>     at OpenBCI_GUI$ControlPanel.CPmouseReleased(OpenBCI_GUI.java:2472)
>     at OpenBCI_GUI.mouseReleased(OpenBCI_GUI.java:1018)
>     at processing.core.PApplet.mouseReleased(PApplet.java:2773)
>     at processing.core.PApplet.handleMouseEvent(PApplet.java:2682)
>     at processing.core.PApplet.dequeueEvents(PApplet.java:2596)
>     at processing.core.PApplet.handleDraw(PApplet.java:2407)
>     at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:654)
>     at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:691)
>     at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:673)
>     at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:442)
>     at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
>     at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
>     at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:680)
>     at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:77)
>     at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:451)
>     at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
>     at java.util.TimerThread.mainLoop(Timer.java:555)
>     at java.util.TimerThread.run(Timer.java:505)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenBCI/OpenBCI_Processing/issues/29>.
>



-- 
*Tao Lin *
Computer Science Department
Columbia University
Email: tl2699@columbia.edu
Linkedin: https://www.linkedin.com/pub/tao-lin/a6/167/450

**Comment by teonlamont** [comment]
got it, just had to copy over the libraries into the Documents folder.

**Comment by OisinMoran** [comment]
Hey I'm having this exact same problem. How exactly did you solve this @teonbrooks?

**Comment by teonbrooks** [comment]
@OisinMoran I haven't used this in a while. I think that [v2.0](https://github.com/OpenBCI/OpenBCI_GUI_v2.0) that's going to be released soon will have all of this solved.
